- name: Restart tmux session
  hosts: localhost  # Replace with the target hosts or groups where tmux needs to be restarted

  tasks:
    - name: Stop tmux session (if running)
      shell: "tmux kill-server"
      ignore_errors: yes    # Ignore errors if tmux is not running


- hosts: localhost
  vars:
    tmux_conf_literal: |
      # Set default shell to zsh instead of bash
      set-option -g default-shell /bin/zsh

      # Keep as much history as possible
      set -g history-limit 100000

      # Smart pane switching with awareness of vim splits
      is_vim='echo "#{pane_current_command}" | grep -iqE "(^|\/)g?(view|n?vim?)(diff)?$"'
      bind -n C-h if-shell "$is_vim" "send-keys C-h" "select-pane -L"
      bind -n C-j if-shell "$is_vim" "send-keys C-j" "select-pane -D"
      bind -n C-k if-shell "$is_vim" "send-keys C-k" "select-pane -U"
      bind -n C-l if-shell "$is_vim" "send-keys C-l" "select-pane -R"
      bind -n C-\\ if-shell "$is_vim" "send-keys C-\\" "select-pane -l"
      unbind d
      bind -n C-d if-shell "$is_vim" "send-keys C-\\" "select-pane -l"


      # Easy window and session switching
      bind -n C-Right next-window
      bind -n C-Left previous-window
      bind -n C-Up switch-client -p
      bind -n C-Down switch-client -n

      # New Window
      bind -n C-t new-window -c "#{pane_current_path}" 
      bind -n C-q kill-pane

      # remap prefix to Control + a
      set -g prefix C-a
      unbind C-b
      bind C-a send-prefix

      # quick window cycling
      unbind ^A
      bind ^A last-window 

      bind-key \\ split-window -h
      bind-key - split-window -v

  roles:
    - role: nephelaiio.tmux